import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import "lenis/dist/lenis.css";

const dm_sans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
export const metadata: Metadata = {
  title: "Medhanye tsegay | Frontend developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={dm_sans.className}>
      <body>{children}</body>
    </html>
  );
}
